# http://about.travis-ci.org/docs/user/build-configuration/
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
before_install:
  - curl -L https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.9/
  - make
  - ./beanstalkd &
  - cd $TRAVIS_BUILD_DIR
matrix:
  allow_failures:
    - rvm: rbx-19mode
script:
  - bundle install
  - bundle exec rake test
gemfile: Gemfile
notifications:
  recipients:
    - nesquena@gmail.com